### ISSUE TITLE
example not working

### ISSUE THREAD

**Issue by opensourcegeek** [avelino/quik#9]
The example from the main page isn't working - not sure if i'm doing something wrong.

from quik import Template

temp = Template("""

<ul>
    #for @user in @users:
        #if @user.age > 18:
        <li><a href="@user.url">@user.username</a></li>
        #end
    #end
</ul>

""")

users = [
    {'username': 'foo', 'url': 'http://...', 'age': 25},
    {'username': 'bar', 'url': 'https://...', 'age': 18}]

print temp.render(locals())

/usr/local/bin/python quik_template_test.py
Traceback (most recent call last):
  File "/Users/opensourcegeek/PycharmProjects/jsf_robot_case_generator/tests/py/quik_template_test.py", line 18, in <module>
    print temp.render(users)
  File "/usr/local/lib/python2.7/site-packages/quik.py", line 27, in render
    self.merge_to(namespace, output, loader)
  File "/usr/local/lib/python2.7/site-packages/quik.py", line 37, in merge_to
    self.ensure_compiled()
  File "/usr/local/lib/python2.7/site-packages/quik.py", line 32, in ensure_compiled
    self.root_element = TemplateBody(self.content)
  File "/usr/local/lib/python2.7/site-packages/quik.py", line 157, in **init**
    self.parse()
  File "/usr/local/lib/python2.7/site-packages/quik.py", line 941, in parse
    raise self.syntax_error('block element')
quik.TemplateSyntaxError: line 7, column 5: expected block element in template body, got: #end
</ul>
 ...

**Comment by avelino** [comment]
error on if syntax, open issue #7
